### PR TITLE
Adds Node Linting

### LINKED ISSUE #17: Node Linting via Yarn
Linting and pretty-printing JavaScript code can help developers catch errors early, make code more legible, and improve overall code quality.

Utilize eslint and prettier to catch code mistakes and formatting issues.

### PR DESCRIPTION
**Pull request by adamweeks**
Fixes #17 

Open to discussion on the rules. Using the [airbnb ruleset](https://github.com/airbnb/javascript) as a baseline.

### CODE REVIEW

**Review by Aaron-TheCreator — APPROVED** [review]
should this PR be merged before #16 ?

**Comment by adamweeks** [comment]
> should this PR be merged before #16 ?

@Aaron-TheCreator this is tech debt, so please go ahead and prioritize the deliverables. Once #16 is merged, I'll update this PR.

**Review by DavidLiedle — APPROVED** [review]
Thanks for adding this, @adamweeks ! Looks great, and will help us keep a uniform presentation of our Node code to Developers. <3

**Comment by DavidLiedle** [comment]
Notes: this covers Node, but we should also consider linting for other languages that are or will be represented in this repo, such as the PHP file (so far). Also, it uses Yarn, which is an additional install. We should talk about that in the README, as it goes beyond the included npm that comes with Node in a barebones approach.

**Pull request merged**
